name: Build and Run Singularity Container

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-run:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Checkout code with submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Show submodule status
      run: git submodule status

    - name: install dependencies for Singularity 
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          uuid-dev \
          build-essential \
          libseccomp-dev \
          pkg-config \
          squashfs-tools \
          cryptsetup \
          curl \
          wget \
          git \
          uidmap \
          runc # or crun (but runc is more widely supported)

    - name: install Go
      run: |
        export GOVERSION=1.17.3 OS=linux ARCH=amd64
        wget -O /tmp/go${GOVERSION}.${OS}-${ARCH}.tar.gz \
          https://dl.google.com/go/go${GOVERSION}.${OS}-${ARCH}.tar.gz
        sudo tar -C /usr/local -xzf /tmp/go${GOVERSION}.${OS}-${ARCH}.tar.gz

    - name : setup Env for GO
      run: echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.bashrc && source ~/.bashrc

    - name: Install Singularity
      run: |
        wget https://github.com/sylabs/singularity/releases/download/v4.1.3/singularity-ce_4.1.3-focal_amd64.deb
        sudo apt-get install -y libfuse2 fuse2fs
        sudo dpkg -i singularity-ce_4.1.3-focal_amd64.deb
        sudo apt-get install -f

    - name : verifyVersion
      run: singularity --version

    - name: Build Singularity Image
      run: |
        sudo singularity build grayscale.sif Singularity.def

    - name: Run Application in Singularity
      run: |
        singularity run grayscale.sif input output Average

    - name: Upload output images
      uses: actions/upload-artifact@v4
      with:
        name: pgm-results
        path: output/

    - name: Upload grayscale.sif
      uses: actions/upload-artifact@v4
      with:
        name: grayscale-sif
        path: grayscale.sif

    - name: Convert job.sh to UNIX line endings
      run: dos2unix job.sh || true

    - name: Setup SSH key from GitHub Secret
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.G100_SSH_KEY }}" > ~/.ssh/my_key
        chmod 600 ~/.ssh/my_key
        ssh-keyscan -H ${{ secrets.SLURM_HOST }} >> ~/.ssh/known_hosts

    - name: Use passphrase via fake ssh-askpass
      run: |
        echo '#!/bin/sh' > /tmp/askpass.sh
        echo "echo '${{ secrets.G100_SSH_PASSPHRASE }}'" >> /tmp/askpass.sh
        chmod +x /tmp/askpass.sh

        export DISPLAY=:0
        export SSH_ASKPASS=/tmp/askpass.sh
        eval "$(ssh-agent -s)"
        setsid ssh-add ~/.ssh/my_key < /dev/null
    - name: Transfer job script and sif file to cluster via scp
      run: |
#        scp -i ~/.ssh/my_key -o StrictHostKeyChecking=no grayscale.sif job.sh ${{ secrets.SLURM_USER }}@${{ secrets.SLURM_HOST }}:~/seproject/
        scp -o StrictHostKeyChecking=no grayscale.sif job.sh ${{ secrets.SLURM_USER }}@${{ secrets.SLURM_HOST }}:~/seproject/

    - name: Submit job to cluster via SSH
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SLURM_USER }}@${{ secrets.SLURM_HOST }} "cd ~/seproject && sbatch job.sh"

#    - name: Remove old host-key And Add new host-key to known_hosts
#      run: |
#        mkdir -p ~/.ssh
#        touch ~/.ssh/known_hosts
#        ssh-keygen -R ${{ secrets.SLURM_HOST }} || true
#        ssh-keyscan -H ${{ secrets.SLURM_HOST }} >> ~/.ssh/known_host

#    - name: Transfer job script and sif file to cluster via scp
#      env:
#        SLURM_USER: ${{ secrets.SLURM_USER }}
#        SLURM_HOST: ${{ secrets.SLURM_HOST }}
#        SLURM_PASSWORD: ${{ secrets.SLURM_PASSWORD }}
#      run: |
#        sudo apt-get install -y sshpass
#        sshpass -p "${{ secrets.SLURM_PASSWORD }}" scp \
#          -o UserKnownHostsFile=/dev/null \
#          -o StrictHostKeyChecking=no \
#          -o PubkeyAuthentication=no \
#          grayscale.sif ${{ secrets.SLURM_USER }}@${{ secrets.SLURM_HOST }}:~/seproject/
#
#        sshpass -p "${{ secrets.SLURM_PASSWORD }}" scp \
#          -o UserKnownHostsFile=/dev/null \
#          -o StrictHostKeyChecking=no \
#          -o PubkeyAuthentication=no \
#          job.sh ${{ secrets.SLURM_USER }}@${{ secrets.SLURM_HOST }}:~/seproject/

#    - name: Submit job to cluster via SSH
#      env:
#        SLURM_USER: ${{ secrets.SLURM_USER }}
#        SLURM_HOST: ${{ secrets.SLURM_HOST }}
#        SLURM_PASSWORD: ${{ secrets.SLURM_PASSWORD }}
#      run: |
#        sshpass -p "${{ secrets.SLURM_PASSWORD }}" ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ${{ secrets.SLURM_USER }}@${{ secrets.SLURM_HOST }} \
#        "cd ~/seproject && sbatch job.sh"
